[project]
name = "opennose"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "manifold3d>=3.5.2",
    "matplotlib>=3.10.0",
    "networkx>=3.6.1",
    "numpy>=2.5.2",
    "pyglet<2",
    "pymoo>=0.6.1.5",
    "rtree>=1.4.1",
    "scipy>=1.18.1",
    "shapely>=2.1.2",
    "trimesh>=5.1.0",
]
